#ifndef SCRATCH3CONVERT_H
#define SCRATCH3CONVERT_H

#define SCRATCH3CONVERT_VER 20190218l

#ifdef __cplusplus
	#define CAPI extern "C"
#else
	#define CAPI
#endif

#ifdef SCRATCH3CONVERT_LIBRARY_EXPORT
	#ifdef _MSC_VER
		#define SC3CONVERT_LIBAPI CAPI __declspec(dllexport)
	#else
		#define SC3CONVERT_LIBAPI CAPI extern
	#endif
#else
	#ifdef _MSC_VER
		#define SC3CONVERT_LIBAPI CAPI __declspec(dllimport)
	#else
		#define SC3CONVERT_LIBAPI CAPI extern
	#endif
#endif

#define SC3CONVERT_SUCCESS						+0x01

#define SC3CONVERT_EXCEPTION_UNZIPOPENZIP		-0x01
#define SC3CONVERT_EXCEPTION_UNZIPGLOBALINFO	-0x02
#define SC3CONVERT_EXCEPTION_UNZIPFILEINFO		-0x03
#define SC3CONVERT_EXCEPTION_UNZIPOPENFILE		-0x04
#define SC3CONVERT_EXCEPTION_UNZIPCREATEFILE	-0x05
#define SC3CONVERT_EXCEPTION_UNZIPREADFILE		-0x06
#define SC3CONVERT_EXCEPTION_UNZIPREADNEXTFILE	-0x07

#define SC3CONVERT_EXCEPTION_ZIPCREATEZIP		-0x01

#define SC3CONVERT_EXCEPTION_CONVOPENFILE		-0x21

SC3CONVERT_LIBAPI int sc3convert_convert(const char *name);

#endif
